import json
import os

stations = {
    "yandexstation": "Яндекс.Станция",
    "yandexstation_2": "Яндекс.Станция Макс",
    "yandexmini": "Яндекс.Станция Мини",
    "yandexmini_2": "Яндекс.Станция Мини 2",
    "yandexmicro": "Яндекс.Станция Лайт",
    "yandexmidi": "Яндекс.Станция 2",
    "cucumber": "Яндекс.Станция Миди",
    "chiron": "Яндекс.Станция Дуо Макс",
}

name = input("Введите ваш никнейм (напр: ivan123): ").strip().split(' ')[0]

print("Выберите вашу Станцию из списка:")
keys = list(stations.keys())
for st in keys:
    print(f'\t{keys.index(st)}: {stations[st]}')
stnum = input("Число: ")
try:
    station = keys[int(stnum)]
except:
    print("Некорректное число!")
    exit(1)

description = input("Введите описание пресета: ").strip()

usercstr = input("Включить Room Correction? (д/Н): ")
use_rc = usercstr.startswith(('д', 'Д', 'y', 'Y'))

path = os.path.join("presets", f"{station.replace('_', '')}_{name.lower()}.py")

print("\n\n"
      "Конфигурация\n"
      "------------\n"
      f"Автор: {name}\n"
      f"Описание: {description}\n"
      f"Модель: {stations[station]}\n"
      f"Room Correction: {"Включено" if use_rc else "Выключено"}\n\n"
      f"Путь к пресету: {path}")

preset = {
    'author': name,
    'description': description,
    'device': station,
    'use_room_correction': use_rc,
    'bands': [
        {
            "freq": 123,
            "width": 123,
            "gain": 12,
        }
    ]
}

if os.access(path, os.F_OK):
    print("\n[!] Такой пресет уже существует")
    exit(1)

with open(path, 'w') as pr:
    s = json.dumps(preset, indent=4).replace('true', 'True').replace('false', 'False')
    pr.write(f"preset = {s}")

with open('preset.py', 'r+') as pr:
    presets = pr.read()
    presets = presets.replace('# autogenerated', f'# autogenerated\nimport presets.{station}_{name}')
    presets = presets.replace('presets = [', f'presets = [\n    presets.{station}_{name}.preset,')
    pr.seek(0)
    pr.write(presets)

